In [1]:
# Dependencies
import pandas as pd
import re

In [23]:
#url = f'http://www.espn.com/nfl/powerrankings/_/year/{year}/week/{week}'
url = 'http://www.espn.com/nfl/powerrankings/_/year/2009/week/1'

In [24]:
tables = pd.read_html(url)
tables

[                               0                             1  \
 0    2009 Power Rankings: Week 1   2009 Power Rankings: Week 1
 1                           RANK                 TEAM / RECORD
 2                              1                  Steelers12-4
 3                              2                  Patriots11-5
 4                              3                    Giants12-4
 5                              4                   Eagles9-6-1
 6                              5                   Chargers8-8
 7                              6                     Colts12-4
 8                              7                    Titans13-3
 9                              8                   Falcons11-5
 10                             9                   Vikings10-6
 11                            10                    Ravens11-5
 12                            11                      Bears9-7
 13                            12                   Packers6-10
 14                            13                  Cardinals9-7
 15                            14                  Panthers12-4
 16                            15                  Seahawks4-12
 17                            16                  Dolphins11-5
 18                            17                    Cowboys9-7
 19                            18                     Saints8-8
 20                            19                     Texans8-8
 21                            20                   Redskins8-8
 22                            21                      Bills7-9
 23                            22                      49ers7-9
 24                            23                       Jets9-7
 25                            24                 Bengals4-11-1
 26                            25                   Jaguars5-11
 27                            26                 Buccaneers9-7
 28                            27                    Broncos8-8
 29                            28                    Browns4-12
 30                            29                    Chiefs2-14
 31                            30                   Raiders5-11
 32                            31                      Rams2-14
 33                            32                     Lions0-16
 34  Biggest Jump:5Biggest Drop:3  Biggest Jump:5Biggest Drop:3

                                2  \
 0    2009 Power Rankings: Week 1
 1                       TRENDING
 2                 --Last Week: 1
 3                 --Last Week: 2
 4                 --Last Week: 3
 5                 --Last Week: 4
 6                  1Last Week: 6
 7                  1Last Week: 5
 8                 --Last Week: 7
 9                 --Last Week: 8
 10                --Last Week: 9
 11               --Last Week: 10
 12                2Last Week: 13
 13                5Last Week: 17
 14                1Last Week: 12
 15                3Last Week: 11
 16                3Last Week: 18
 17                1Last Week: 15
 18                3Last Week: 14
 19                1Last Week: 19
 20                3Last Week: 16
 21               --Last Week: 20
 22               --Last Week: 21
 23               --Last Week: 22
 24               --Last Week: 23
 25               --Last Week: 24
 26               --Last Week: 25
 27               --Last Week: 26
 28               --Last Week: 27
 29               --Last Week: 28
 30               --Last Week: 29
 31               --Last Week: 30
 32               --Last Week: 31
 33               --Last Week: 32
 34  Biggest Jump:5Biggest Drop:3

                                                     3  \
 0                         2009 Power Rankings: Week 1
 1                                            COMMENTS
 2   They're loaded with talent and their coach kno...
 3   QB Tom Brady's broad shoulders have to carry a...
 4   The Giants have concerns on defense, but they ...
 5   QB Donovan McNabb isn't wild about Wildcat, bu...
 6   Even if the Chargers get caught up in the hype...
 7   Left tackle is the one big issue, but they'll ...
 8   Life gets easier after difficult first six gam...
 9   A year of seasoning for Matt Ryan should put t...
 10  Schism or not, Brett Favre makes this team a c...
 11  They're lucky WR Derrick Mason decided to retu...
 12  I still don't see how Jay Cutler can play his ...
 13  It all comes down to whether that defense can ...
 14  QB Kurt Warner and key veterans sound a bit co...
 15  It's tough to set expectations for this group ...
 16  The Seahawks are rising in the rankings after ...
 17  The Dolphins hope to avert the three-game drop...
 18  WR Roy Williams is catching everything in prac...
 19  Skepticism seems appropriate until the Saints ...
 20  LB Brian Cushing alone can't solve the defensi...
 21  QB Jason Campbell appears improved now that co...
 22  Firing offensive coordinator Turk Schonert nin...
 23  Establishing a hard-nosed ground game was the ...
 24  Mark Sanchez continues to appear confident as ...
 25  Love this year's version of "Hard Knocks." Unf...
 26  With three division games in first four, the J...
 27  A defensive-minded rookie coach plus new start...
 28  It has to take a while for team to buy in afte...
 29  I just can't see new coach Eric Mangini turnin...
 30  The Chiefs have a chance to climb if they can ...
 31  Will QB JaMarcus Russell start to quiet critic...
 32  The schedule makers did new coach Steve Spagnu...
 33  New coach Jim Schwartz will make the Lions bet...
 34                       Biggest Jump:5Biggest Drop:3

                               4
 0   2009 Power Rankings: Week 1
 1                           NaN
 2                           NaN
 3                           NaN
 4                           NaN
 5                           NaN
 6                           NaN
 7                           NaN
 8                           NaN
 9                           NaN
 10                          NaN
 11                          NaN
 12                          NaN
 13                          NaN
 14                          NaN
 15                          NaN
 16                          NaN
 17                          NaN
 18                          NaN
 19                          NaN
 20                          NaN
 21                          NaN
 22                          NaN
 23                          NaN
 24                          NaN
 25                          NaN
 26                          NaN
 27                          NaN
 28                          NaN
 29                          NaN
 30                          NaN
 31                          NaN
 32                          NaN
 33                          NaN
 34                          NaN  ,
                                                    0
 0                                           Glossary
 1  The rankings were determined by ESPN's Power P...]

In [26]:
tables[0]

,0,1,2,3,4
0,2009 Power Rankings: Week 1,2009 Power Rankings: Week 1,2009 Power Rankings: Week 1,2009 Power Rankings: Week 1,2009 Power Rankings: Week 1
1,RANK,TEAM / RECORD,TRENDING,COMMENTS,NaN
2,1,Steelers12-4,--Last Week: 1,They're loaded with talent and their coach kno...,NaN
3,2,Patriots11-5,--Last Week: 2,QB Tom Brady's broad shoulders have to carry a...,NaN
4,3,Giants12-4,--Last Week: 3,"The Giants have concerns on defense, but they ...",NaN
5,4,Eagles9-6-1,--Last Week: 4,"QB Donovan McNabb isn't wild about Wildcat, bu...",NaN
6,5,Chargers8-8,1Last Week: 6,Even if the Chargers get caught up in the hype...,NaN
7,6,Colts12-4,1Last Week: 5,"Left tackle is the one big issue, but they'll ...",NaN
8,7,Titans13-3,--Last Week: 7,Life gets easier after difficult first six gam...,NaN
9,8,Falcons11-5,--Last Week: 8,A year of seasoning for Matt Ryan should put t...,NaN
10,9,Vikings10-6,--Last Week: 9,"Schism or not, Brett Favre makes this team a c...",NaN
11,10,Ravens11-5,--Last Week: 10,They're lucky WR Derrick Mason decided to retu...,NaN
12,11,Bears9-7,2Last Week: 13,I still don't see how Jay Cutler can play his ...,NaN
13,12,Packers6-10,5Last Week: 17,It all comes down to whether that defense can ...,NaN
14,13,Cardinals9-7,1Last Week: 12,QB Kurt Warner and key veterans sound a bit co...,NaN
15,14,Panthers12-4,3Last Week: 11,It's tough to set expectations for this group ...,NaN
16,15,Seahawks4-12,3Last Week: 18,The Seahawks are rising in the rankings after ...,NaN
17,16,Dolphins11-5,1Last Week: 15,The Dolphins hope to avert the three-game drop...,NaN
18,17,Cowboys9-7,3Last Week: 14,WR Roy Williams is catching everything in prac...,NaN
19,18,Saints8-8,1Last Week: 19,Skepticism seems appropriate until the Saints ...,NaN
20,19,Texans8-8,3Last Week: 16,LB Brian Cushing alone can't solve the defensi...,NaN
21,20,Redskins8-8,--Last Week: 20,QB Jason Campbell appears improved now that co...,NaN
22,21,Bills7-9,--Last Week: 21,Firing offensive coordinator Turk Schonert nin...,NaN
23,22,49ers7-9,--Last Week: 22,Establishing a hard-nosed ground game was the ...,NaN
24,23,Jets9-7,--Last Week: 23,Mark Sanchez continues to appear confident as ...,NaN
25,24,Bengals4-11-1,--Last Week: 24,"Love this year's version of ""Hard Knocks."" Unf...",NaN
26,25,Jaguars5-11,--Last Week: 25,"With three division games in first four, the J...",NaN
27,26,Buccaneers9-7,--Last Week: 26,A defensive-minded rookie coach plus new start...,NaN
28,27,Broncos8-8,--Last Week: 27,It has to take a while for team to buy in afte...,NaN
29,28,Browns4-12,--Last Week: 28,I just can't see new coach Eric Mangini turnin...,NaN
30,29,Chiefs2-14,--Last Week: 29,The Chiefs have a chance to climb if they can ...,NaN
31,30,Raiders5-11,--Last Week: 30,Will QB JaMarcus Russell start to quiet critic...,NaN
32,31,Rams2-14,--Last Week: 31,The schedule makers did new coach Steve Spagnu...,NaN
33,32,Lions0-16,--Last Week: 32,New coach Jim Schwartz will make the Lions bet...,NaN
34,Biggest Jump:5Biggest Drop:3,Biggest Jump:5Biggest Drop:3,Biggest Jump:5Biggest Drop:3,Biggest Jump:5Biggest Drop:3,NaN

In [5]:
df_table = tables[2]
cols = [2,3,4]
df_table.drop(df_table.columns[cols],axis=1,inplace=True)

In [6]:
df_table = df_table.rename(columns={0: "Rank", 1: "Team"})
df_table

,Rank,Team
0,2007 Power Rankings: Week 1,2007 Power Rankings: Week 1
1,RANK,TEAM / RECORD
2,1,Patriots12-4
3,2,Colts12-4
4,3,Chargers14-2
5,4,Bears13-3
6,5,Ravens13-3
7,6,Saints10-6
8,7,Eagles10-6
9,8,Cowboys9-7
10,9,Broncos9-7
11,10,Seahawks9-7
12,11,Bengals8-8
13,12,Jaguars8-8
14,13,Steelers8-8
15,14,Jets10-6
16,15,Panthers8-8
17,16,49ers7-9
18,17,Rams8-8
19,18,Giants8-8
20,19,Redskins5-11
21,20,Dolphins6-10
22,21,Bills7-9
23,22,Titans8-8
24,23,Cardinals5-11
25,24,Packers8-8
26,25,Lions3-13
27,26,Chiefs9-7
28,27,Vikings6-10
29,28,Buccaneers4-12
30,29,Texans6-10
31,30,Raiders2-14
32,31,Falcons7-9
33,32,Browns4-12
34,Biggest Jump:9Biggest Drop:12Make your ownPowe...,Biggest Jump:9Biggest Drop:12Make your ownPowe...

In [7]:
df_table = df_table.drop([0, 1, 34])
df_table = df_table.reset_index(drop=True)
df_table

   Rank            Team
0     1    Patriots12-4
1     2       Colts12-4
2     3    Chargers14-2
3     4       Bears13-3
4     5      Ravens13-3
5     6      Saints10-6
6     7      Eagles10-6
7     8      Cowboys9-7
8     9      Broncos9-7
9    10     Seahawks9-7
10   11      Bengals8-8
11   12      Jaguars8-8
12   13     Steelers8-8
13   14        Jets10-6
14   15     Panthers8-8
15   16        49ers7-9
16   17         Rams8-8
17   18       Giants8-8
18   19    Redskins5-11
19   20    Dolphins6-10
20   21        Bills7-9
21   22       Titans8-8
22   23   Cardinals5-11
23   24      Packers8-8
24   25       Lions3-13
25   26       Chiefs9-7
26   27     Vikings6-10
27   28  Buccaneers4-12
28   29      Texans6-10
29   30     Raiders2-14
30   31      Falcons7-9
31   32      Browns4-12

In [8]:
test_str = df_table['Team'][0]

In [9]:
#shawns = (filter(lambda x: x.isalpha(), test_str))
#print(shawns)
#for x in shawns:
#    print(x)
res = [re.findall(r'(\w+?)(\d+)', test_str)[0] ] 
print(res[0][0])

Patriots

In [10]:
for i,r in df_table.iterrows():
    value = df_table.loc[i, "Team"]
    team = [re.findall(r'(\w+?)(\d+)', value)[0] ] 
    df_table.loc[i, "Team"] = team[0][0]
#final_df['Team'] = final_df['Team'].str.replace(r'\D', '')
df_table

   Rank        Team
0     1    Patriots
1     2       Colts
2     3    Chargers
3     4       Bears
4     5      Ravens
5     6      Saints
6     7      Eagles
7     8     Cowboys
8     9     Broncos
9    10    Seahawks
10   11     Bengals
11   12     Jaguars
12   13    Steelers
13   14        Jets
14   15    Panthers
15   16           4
16   17        Rams
17   18      Giants
18   19    Redskins
19   20    Dolphins
20   21       Bills
21   22      Titans
22   23   Cardinals
23   24     Packers
24   25       Lions
25   26      Chiefs
26   27     Vikings
27   28  Buccaneers
28   29      Texans
29   30     Raiders
30   31     Falcons
31   32      Browns

In [15]:
for i,r in df_table.iterrows():
    team = df_table.loc[i, "Team"]
    if team == '4':
        df_table.loc[i, "Team"] = '49ers'
df_table

   Rank        Team
0     1    Patriots
1     2       Colts
2     3    Chargers
3     4       Bears
4     5      Ravens
5     6      Saints
6     7      Eagles
7     8     Cowboys
8     9     Broncos
9    10    Seahawks
10   11     Bengals
11   12     Jaguars
12   13    Steelers
13   14        Jets
14   15    Panthers
15   16       49ers
16   17        Rams
17   18      Giants
18   19    Redskins
19   20    Dolphins
20   21       Bills
21   22      Titans
22   23   Cardinals
23   24     Packers
24   25       Lions
25   26      Chiefs
26   27     Vikings
27   28  Buccaneers
28   29      Texans
29   30     Raiders
30   31     Falcons
31   32      Browns

In [27]:
years = ['2007','2008','2009','2010','2011','2012','2013','2014','2015']
weeks = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17']
seasons = []
cols = [2,3,4]

for year in years:
    df_list = []
    for week in weeks:
        url = f'http://www.espn.com/nfl/powerrankings/_/year/{year}/week/{week}'
        data = pd.read_html(url)
        if year == '2007' or year == '2008':
            df_table = data[2]
        else:
            df_table = data[0]
        print(year + ' ' + week)
        df_table.drop(df_table.columns[cols],axis=1,inplace=True)
        df_table = df_table.rename(columns={0: "Rank", 1: "Team"})
        df_table = df_table.drop([0, 1, 34])
        df_table = df_table.reset_index(drop=True)
        for i,r in df_table.iterrows():
            value = df_table.loc[i, "Team"]
            team = [re.findall(r'(\w+?)(\d+)', value)[0] ] 
            df_table.loc[i, "Team"] = team[0][0]
        for i,r in df_table.iterrows():
            team = df_table.loc[i, "Team"]
            if team == '4':
                df_table.loc[i, "Team"] = '49ers'
        df_list.append(df_table)
    seasons.append(df_list)
print(len(seasons))

2007 1
2007 2
2007 3
2007 4
2007 5
2007 6
2007 7
2007 8
2007 9
2007 10
2007 11
2007 12
2007 13
2007 14
2007 15
2007 16
2007 17
2008 1
2008 2
2008 3
2008 4
2008 5
2008 6
2008 7
2008 8
2008 9
2008 10
2008 11
2008 12
2008 13
2008 14
2008 15
2008 16
2008 17
2009 1
2009 2
2009 3
2009 4
2009 5
2009 6
2009 7
2009 8
2009 9
2009 10
2009 11
2009 12
2009 13
2009 14
2009 15
2009 16
2009 17
2010 1
2010 2
2010 3
2010 4
2010 5
2010 6
2010 7
2010 8
2010 9
2010 10
2010 11
2010 12
2010 13
2010 14
2010 15
2010 16
2010 17
2011 1
2011 2
2011 3
2011 4
2011 5
2011 6
2011 7
2011 8
2011 9
2011 10
2011 11
2011 12
2011 13
2011 14
2011 15
2011 16
2011 17
2012 1
2012 2
2012 3
2012 4
2012 5
2012 6
2012 7
2012 8
2012 9
2012 10
2012 11
2012 12
2012 13
2012 14
2012 15
2012 16
2012 17
2013 1
2013 2
2013 3
2013 4
2013 5
2013 6
2013 7
2013 8
2013 9
2013 10
2013 11
2013 12
2013 13
2013 14
2013 15
2013 16
2013 17
2014 1
2014 2
2014 3
2014 4
2014 5
2014 6
2014 7
2014 8
2014 9
2014 10
2014 11
2014 12
2014 13
2014 14
2014 15
2014 16
2014 17
2015 1
2015 2
2015 3
2015 4
2015 5
2015 6
2015 7
2015 8
2015 9
2015 10
2015 11
2015 12
2015 13
2015 14
2015 15
2015 16
2015 17
9