In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("cleaned.csv")
df

,Unnamed: 0,Week,Date,Winner,Loser,PtsW,PtsL,YdsW,TOW,YdsL,...,net_ydsl,net_tovw,net_tovl,Year,Favorite,spread_favorite,team_home,team_away,w_pwr_rnk,l_pwr_rnk
0,0,1,6-Sep,Indianapolis Colts,New Orleans Saints,41,10,452,1,293,...,0,0,0,2007,Indianapolis Colts,-5.5,Indianapolis Colts,New Orleans Saints,2,6
1,1,1,9-Sep,Carolina Panthers,St. Louis Rams,27,13,385,2,238,...,0,0,0,2007,St. Louis Rams,-1.0,St. Louis Rams,Carolina Panthers,15,17
2,2,1,9-Sep,Minnesota Vikings,Atlanta Falcons,24,3,302,1,265,...,0,0,0,2007,Minnesota Vikings,-3.0,Minnesota Vikings,Atlanta Falcons,27,31
3,3,1,9-Sep,Washington Redskins,Miami Dolphins,16,13,400,2,273,...,0,0,0,2007,Washington Redskins,-3.0,Washington Redskins,Miami Dolphins,19,20
4,4,1,9-Sep,Denver Broncos,Buffalo Bills,15,14,470,1,184,...,0,0,0,2007,Denver Broncos,-3.0,Buffalo Bills,Denver Broncos,9,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,2299,17,3-Jan,San Francisco 49ers,St. Louis Rams,19,16,458,1,364,...,-1030,4,-3,2015,St. Louis Rams,-3.0,San Francisco 49ers,St. Louis Rams,31,17
2300,2300,17,3-Jan,Carolina Panthers,Tampa Bay Buccaneers,38,10,366,2,386,...,548,-19,4,2015,Carolina Panthers,-10.0,Carolina Panthers,Tampa Bay Buccaneers,2,22
2301,2301,17,3-Jan,Seattle Seahawks,Arizona Cardinals,36,6,354,0,232,...,1508,-4,-12,2015,Arizona Cardinals,-6.0,Arizona Cardinals,Seattle Seahawks,10,1
2302,2302,17,3-Jan,Kansas City Chiefs,Oakland Raiders,23,17,339,2,205,...,-325,-15,0,2015,Kansas City Chiefs,-6.5,Kansas City Chiefs,Oakland Raiders,7,13
2303,2303,17,3-Jan,Minnesota Vikings,Green Bay Packers,20,13,242,2,350,...,-302,-5,-5,2015,Green Bay Packers,-3.0,Green Bay Packers,Minnesota Vikings,11,8

In [5]:
df3 = df

home = []
point_dif = []
yards_dif = []
turn_dif = []
rank_dif = []
spread = []
win = []
winspread = []

for i in range(0, len(df3)):
    #print(df3.iloc[i]["Winner"])
    dif = df3.iloc[i]["PtsW"] - df3.iloc[i]["PtsL"]
    
    #home team wins
    if(df3.iloc[i]["Winner"] == df3.iloc[i]["team_home"]):
        
        #home team won
        home.append(1)
        if(dif == 0):
            win.append(0.5)
        else:
            win.append(1)
        point_dif.append(df3.iloc[i]['net_ptsw'])
        yards_dif.append(df3.iloc[i]['net_ydsw'])
        turn_dif.append(df3.iloc[i]['net_tovw'])
        rank_dif.append(df3.iloc[i]['w_pwr_rnk'])
        if df3.iloc[i]['Winner'] == df3.iloc[i]['Favorite']:
            spread.append(df3.iloc[i]['spread_favorite'])
            if(dif > abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(1)
            elif(dif == abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(0.5)
            else:
                winspread.append(0)
        elif df3.iloc[i]['spread_favorite'] == 0:
            spread.append(0)
            if(dif == 0):
                winspread.append(0.5)
            else:
                winspread.append(1)
        else:
            spread.append(-int(df3.iloc[i]['spread_favorite']))
            winspread.append(1)
        
        #away data lost
        home.append(0)
        if(dif == 0):
            win.append(0.5)
        else:
            win.append(0)
        point_dif.append(df3.iloc[i]['net_ptsl'])
        yards_dif.append(df3.iloc[i]['net_ydsl'])
        turn_dif.append(df3.iloc[i]['net_tovl'])
        rank_dif.append(df3.iloc[i]['l_pwr_rnk'])
        if df3.iloc[i]['Winner'] == df3.iloc[i]['Favorite']:
            spread.append(-df3.iloc[i]['spread_favorite'])
            if(dif < abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(1)
            elif(dif == abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(0.5)
            else:
                winspread.append(0)
        elif df3.iloc[i]['spread_favorite'] == 0:
            spread.append(0)
            if(dif == 0):
                winspread.append(0.5)
            else:
                winspread.append(0)
        else:
            spread.append(int(df3.iloc[i]['spread_favorite']))
            winspread.append(0)
        
    #home team loses
    else:
        
        #home team lost
        home.append(1)
        if(dif == 0):
            win.append(0.5)
        else:
            win.append(0)
        point_dif.append(df3.iloc[i]['net_ptsl'])
        yards_dif.append(df3.iloc[i]['net_ydsl'])
        turn_dif.append(df3.iloc[i]['net_tovl'])
        rank_dif.append(df3.iloc[i]['l_pwr_rnk'])
        if df3.iloc[i]['Winner'] == df3.iloc[i]['Favorite']:
            spread.append(-df3.iloc[i]['spread_favorite'])
            if(dif < abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(1)
            elif(dif == abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(0.5)
            else:
                winspread.append(0)
        elif df3.iloc[i]['spread_favorite'] == 0:
            spread.append(0)
            if(dif == 0):
                winspread.append(0.5)
            else:
                winspread.append(0)
        else:
            spread.append(int(df3.iloc[i]['spread_favorite']))
            winspread.append(0)
            
        #away team won
        home.append(0)
        if(dif == 0):
            win.append(0.5)
        else:
            win.append(1)
        point_dif.append(df3.iloc[i]['net_ptsw'])
        yards_dif.append(df3.iloc[i]['net_ydsw'])
        turn_dif.append(df3.iloc[i]['net_tovw'])
        rank_dif.append(df3.iloc[i]['w_pwr_rnk'])
        if df3.iloc[i]['Winner'] == df3.iloc[i]['Favorite']:
            spread.append(df3.iloc[i]['spread_favorite'])
            if(dif > abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(1)
            elif(dif == abs(df3.iloc[i]['spread_favorite'])):
                winspread.append(0.5)
            else:
                winspread.append(0)
        elif df3.iloc[i]['spread_favorite'] == 0:
            spread.append(0)
            if(dif == 0):
                winspread.append(0.5)
            else:
                winspread.append(1)
        else:
            spread.append(-int(df3.iloc[i]['spread_favorite']))
            winspread.append(1)

In [7]:
final_df = pd.DataFrame({"home": home, "net_points": point_dif, "net_yard": yards_dif, "net_turn": turn_dif, "weekly_rank": rank_dif, "spread": spread, "Win": win, "WinSpread": winspread})
final_df

,home,net_points,net_yard,net_turn,weekly_rank,spread,Win,WinSpread
0,1,0,0,0,2,-5.5,1.0,1.0
1,0,0,0,0,6,5.5,0.0,0.0
2,1,0,0,0,17,-1.0,0.0,0.0
3,0,0,0,0,15,1.0,1.0,1.0
4,1,0,0,0,27,-3.0,1.0,1.0
...,...,...,...,...,...,...,...,...
4603,0,116,1268,-4,10,6.0,1.0,1.0
4604,1,112,-104,-15,7,-6.5,1.0,0.0
4605,0,-34,-325,0,13,6.5,0.0,1.0
4606,1,52,-302,-5,8,-3.0,0.0,0.0
4607,0,56,-260,-5,11,3.0,1.0,1.0

In [8]:
final_df.to_csv('new_final_df.csv')